<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>default</LangVersion>
        <TargetFrameworks>net8.0;net9.0;net472;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetZip.NetStandard" />
      <PackageReference Include="Huxy" />
      <PackageReference Include="LibGit2Sharp" />
      <PackageReference Include="NLog" />
      <PackageReference Include="Nuke.Utilities" />
      <PackageReference Include="System.Memory" />
      <PackageReference Include="System.Net.Http" />
      <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chrono.Core.Test" />
    </ItemGroup>

</Project>
