= Chrono

Current Version:
include::version.yml[lines="3"]

== 📚 About 
Chrono is a git versioning tool with a focus on being customizable and easy to configure.

It is inspired by the likes of https://github.com/GitTools/GitVersion[GitVersion] and https://github.com/dotnet/Nerdbank.GitVersioning[Nerdbank.Gitversioning].

=== ❗ Important

This project is by now means done. Its in active development and while the format of the version.yml will probably not change drastically the cli and nuget package for the msbuild task might :)  

=== 🔮 Planned features

- [ ] Git branch tools (release, tag)
- [ ] smaller size for msbuild package

=== 🚀 Getting started 
Install/Update the dotnet tool using

|===
|Install|Update

a| [source]
----
dotnet tool install -g Chrono
----
a|
[source]
----
dotnet tool install -g Chrono
----

|===

This adds a Directory.Build.props file to the directory from which the tool is run that takes care of installing the DotnetTasks package into your sources. 

Next up create a version.yml (for now only a version.yml at the root of your git repo is supported) 

For the content of version.yml either checkout the minimal example below.
[source, yml]
----
version: "1.0.0"
default:
  versionschema: "{major}.{minor}.{patch}[-]{branchname}[-]{commitShortHash}"
  precision: "minor"  
  release:
    match:
      - "^release/.*"
    versionschema: "{major}.{minor}.{patch}"
----

or read the full link:doc/Version.adoc[documentation].
