= Chrono

Current Version:
include::version.yml[lines="3"]

== 📚 About 
Chrono is a git versioning tool with a focus on being customizable and easy to configure.

It is inspired by the likes of https://github.com/GitTools/GitVersion[GitVersion] and https://github.com/dotnet/Nerdbank.GitVersioning[Nerdbank.Gitversioning].

=== ❗ Important

This project is in active development and while the format of the version.yml will probably not change drastically the cli and nuget package for the msbuild task might :)  


=== 🚀 Getting started 



Install/Update the dotnet tool using

|===
|Install|Update

a| [source]
----
dotnet tool install -g Chrono
----
a|
[source]
----
dotnet tool update -g Chrono
----

|===

Next up create a version.yml (for now only a version.yml at the root of your git repo is supported) 

For the content of version.yml either checkout the minimal example below.
[source, yml]
----
version: "1.0.0"
default:
  versionschema: "{major}.{minor}.{patch}[-]{branchname}[-]{commitShortHash}"
  precision: "minor"  
  release:
    match:
      - "^release/.*"
    versionschema: "{major}.{minor}.{patch}"
----

or read the full link:doc/Version.adoc[documentation].


==== 🕹️ ️Automatic Version stamping (dotnet) 
If you want your dotnet projects to be automatically versioned first make sure your projects are using SDK style project files and dont have existing AssemblyVersion.cs files or the likes present.

Then call 

[source]
----
chrono init
----
in your project root.

This adds a Directory.Build.props file to the directory which takes care of including the DotnetTasks package into your projects.

It also sets the two properties "IncludeSourceRevisionInInformationalVersion" to false and "GenerateAssemblyInfo" to true.

In theory that's it :) 
