<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ToolCommandName>chrono</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

        <PackageId>Chrono.CLI</PackageId>
        <Authors>Ekkehard C. Damisch</Authors>
        <Copyright>Ekkehard C. Damisch</Copyright>
        <PackageProjectUrl>https://github.com/yorschor/Chrono</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>git version dotnet msbuild</PackageTags>
        <RootNamespace>Chrono</RootNamespace>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibGit2Sharp"/>
        <PackageReference Include="Spectre.Console.Cli" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chrono.Core\Chrono.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\icon.png" Pack="true" PackagePath="\"/>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
