name: continuous

on: [push]
permissions: 
  contents: read
  actions: read
  checks: write
    
jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: ./build.sh compile
        
  test:
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/dotnet/sdk:10.0
      steps:
        - uses: actions/checkout@v4
        - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        - run: dotnet test Chrono.slnx --logger trx --results-directory reports
        - uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            files: reports/**/*.trx
